# Generated by Django 3.1 on 2020-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='mainapp.Order', verbose_name='Customer orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payed', 'Order is payed'), ('new', 'New order'), ('in_progress', 'Order processed'), ('ready', 'Order ready'), ('completed', 'Order completed')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
